INTROSPECTION_KEYMAP_C = bov48.c

VPATH += keyboards/gboards

EXTRAKEY_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
COMBO_ENABLE = yes
MAGIC_ENABLE = yes
CAPS_WORD_ENABLE = yes

TAP_DANCE_ENABLE = no
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
RGBLIGHT_ENABLE = no
LEADER_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
AUDIO_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 

LTO_ENABLE = no
